In [2]:
import os
import numpy as np 
import xarray
import pandas as pd

In [18]:
os.system("nohup python clean4_merra.py")

0

In [19]:
# clean1_bcaod550 = pd.read_csv('/data2/edworak/data/cams_lightning_omaod550_clean4.csv')
# clean1_bcaod550
pd.read_csv("/data2/edworak/data/merra_lightning_OCCMASS_clean4.csv")

,Unnamed: 0,year,month,day,hour,minute,second,aod_lat,aod_lon,peak current,C or G,CMI_C14,tlat,tlon,distance(km),OCCMASS,lat_y,lon_y,distance aod(km)
0,0,2019,6,27,20,50,3.478660,53.1479,-122.4336,-42.8,G,-54.086395,53.150426,-122.416843,1.869,0.000004,53.0,-123.125,49.029
1,1,2019,6,27,20,50,3.488611,53.1684,-122.4836,16.9,C,-53.009094,53.147690,-122.486008,1.265,0.000004,53.0,-123.125,46.752
2,2,2019,6,27,20,50,3.491337,53.1469,-122.4170,-13.2,C,-54.086395,53.150426,-122.416843,0.211,0.000004,53.0,-123.125,50.039
3,3,2019,6,27,20,50,3.546841,53.1405,-122.4622,-5.5,C,-53.308350,53.148933,-122.451503,1.292,0.000004,53.0,-123.125,46.956
4,4,2019,6,27,20,50,4.308935,52.6089,-123.6354,4.3,C,-51.034027,52.594750,-123.622042,1.722,0.000004,52.5,-123.750,14.376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,569,2019,6,28,0,38,8.525068,53.9218,-123.9140,2.7,C,-51.093872,53.888143,-123.905783,2.279,0.000005,54.0,-123.750,13.810
1677,570,2019,6,28,0,39,14.909820,53.5473,-124.7629,10.7,C,-54.565216,53.529630,-124.776356,1.869,0.000004,53.5,-125.000,16.532
1678,571,2019,6,28,0,39,14.911943,53.5450,-124.7454,3.8,C,-55.103867,53.530935,-124.741966,0.970,0.000004,53.5,-125.000,17.559
1679,572,2019,6,28,0,39,32.694911,53.8526,-124.4818,3.1,C,-51.752228,53.744115,-124.465576,7.062,0.000005,54.0,-124.375,17.819
1680,573,2019,6,28,0,39,32.694911,53.8526,-124.4818,3.1,C,-51.752228,53.744115,-124.465576,7.062,0.000005,54.0,-123.125,90.334